name: AI translate

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  translate-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.3.0' # Specify your Node.js version

      - name: Install dependencies
        run: pnpm install

      - name: Run reconcile
        run: pnpm run reconcile

      - name: Configure git
        run: |
          git config --global user.name 'AutoTranslator'
          git config --global user.email 'hello@sanity.io'

      - name: Run autotranslate
        run: pnpm run autotranslate
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      # - name: Create or update pull request
      #   if: steps.git-check.outputs.changes == 'true'
      #   run: |
      #     gh pr create --title "Automated Translation Updates" --body "This PR includes automated translation updates." --head translation-updates --base main --repo ${{ github.repository }} --fill
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
