---
name: Assign reviewers

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'locales/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

jobs:
  assign:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20
      - run: corepack enable && pnpm --version
      - run: pnpm install --loglevel=error --ignore-scripts
      - run: |
          pnpm run ci:assign-reviewers
        env:
          PR_NUMBER: ${{ github.event.number }}
